// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkiwiyijyeibbjciakzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhraXdpeWlqeWVpYmJqY2lha3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTY4MzksImV4cCI6MjA2MzczMjgzOX0.2_9L2Ok1eIr1LhVkI7ynkJH3Gy3sAI2caKCtt52Be6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);